<?php

namespace Pipeline\APIBundle\Entity;

use Pipeline\APIBundle\Entity\APIRepository;

use Pipeline\APIBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends APIRepository
{
    /**
     * Replace the underlying find function.
     * 
     * @access public
     * @param mixed $id
     * @return void
     */
    public function find($id) 
    { 
        $user = $this->getUser();
        $em = $this->getEntityManager();
        
        $query = $em->createQuery(
                      'SELECT t
                       FROM APIBundle:Task t
                       WHERE t.id = :id AND t.owner = :user')
                    ->setParameters(array("id" => $id, "user" => $user));
                    
        return $query->getSingleResult();
    }

    /**
     * Temporary task loading function...
     * 
     * @access public
     * @param User $user
     * @return void
     */
    public function findTasksFor(User $user) 
    { 
        $em = $this->getEntityManager();
        $query = $em->createQuery("select t from APIBundle:Task t WHERE t.owner = :user")->setParameter("user", $user);
        
        return $query->getResult();
    }
}
