<?php

namespace Pipeline\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Pipeline\APIBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findTasksFor(User $user) 
    { 
        $em = $this->getEntityManager();
        $query = $em->createQuery("select t from APIBundle:Task t");
        
        return $query->getResult();
    }
}
